version: 0.2

phases:
    install:
        commands:
            - apt-get update
    pre_build:
        commands:
            - npm install
    build:
        commands:
            - npm run build
    post_build:
        commands:
            - aws s3 sync ./dist/angular-front s3://ss3stock --acl 'public-read' --delete
