version: 0.2

env:
    variables:
      S3_BUCKET:"ss3stock"
phases:
    install:
        runtime-versions:
            nodejs: 12
    pre_build:
        commands:
            - npm install
    build:
        commands:
            - npm run build --prod --aot
    post_build:
        commands:
            - aws s3 rm s3://$S3_BUCKET --recursive
            # Copy files from dist to S3
            - aws s3 cp dist/fluxnews-front s3://$S3_BUCKET --recursive
